stages:
  - build
  - test
  - report

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  before_script:
    - apk add --no-cache openjdk21 gradle curl # Install JDK 21
    - chmod +x ./gradlew
  script:
    - ./gradlew clean assemble
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/reports/tests/test
    reports:
      junit: build/test-results/test/TEST-*.xml
    expire_in: 1 week
  rules:
    - when: always
  tags:
    - SET2024

test:
  stage: test
  dependencies:
    - build
  before_script:
    - apk add --no-cache openjdk17 openjdk21 gradle # gitlab creates clean environment per stage, need to install jdk again here
    - chmod +x ./gradlew
  script:
    - ./gradlew clean test # run tests
  artifacts:
    when: always
    paths:
      - build/reports/tests/test
      - build/reports/tests/jacoco
    reports:
      junit: build/test-results/test/TEST-*.xml
    expire_in: 1 week
  rules:
    - when: always
  tags:
    - SET2024

sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  script:
    - sigridci.py --customer Utst --system team03eldorado --source .
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    reports:
      junit: "sigrid-ci-output/sigridci-junit-format-report.xml"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_MERGE_REQUEST_ID
  tags:
    - SET2024

sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  script:
    - sigridci.py --customer Utst --system team03eldorado --source . --publish
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - SET2024
