package org.utwente.Tile;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.*;
import java.awt.Color;
import java.awt.Graphics2D;
import org.mockito.Mockito;
import static org.mockito.Mockito.*;

import java.awt.color.ColorSpace;

import org.junit.jupiter.api.Disabled;
import org.utwente.CaveCoin.CaveCoin;
import org.utwente.Section.SectionController;

import java.awt.image.BufferedImage;
import java.util.ArrayList;

class TileControllerTest {
    private Tile tile;
    private TileView tileView;


    @BeforeEach
    void setUp() {
        // Create a Tile instance with required parameters
        int q = 1;
        int r = 2;
        TileType tileType = TileType.Paddle; // Replace with an actual TileType enum value
        int power = 3;
        ArrayList<CaveCoin> caveCoins = new ArrayList<>();
        boolean isLastWaitingTile = false;

        tile = new Tile(q, r, tileType, power, caveCoins, isLastWaitingTile);
        tileView = new TileView(tile, true); // Provide the required parameters to the constructor.
    }
    /**
     * Method under test: {@link TileController#TileController(Tile, TileView)}
     */
    @Test
    void testNewTileController() {
        // Arrange
        Tile tile = new Tile(1, 1, TileType.Machete, 1, true);

        // Act
        TileController actualTileController = new TileController(tile, tileView);

        // Assert
        Tile tile2 = actualTileController.getTile();
        assertNull(tile2.getBlockade());
        Color tileColor = tile2.getTileColor();
        Color brighterResult = tileColor.brighter();
        Color brighterResult2 = brighterResult.brighter();
        Color brighterResult3 = brighterResult2.brighter();
        Color brighterResult4 = brighterResult3.brighter();
        Color brighterResult5 = brighterResult4.brighter();
        Color brighterResult6 = brighterResult5.brighter();
        assertEquals(-1, brighterResult6.getRGB());
        assertEquals(-10122205, tileColor.getRGB());
        Color darkerResult = brighterResult.darker();
        assertEquals(-10187741, darkerResult.getRGB());
        Color darkerResult2 = darkerResult.darker();
        Color brighterResult7 = darkerResult2.brighter();
        assertEquals(-10187742, brighterResult7.getRGB());
        Color darkerResult3 = tileColor.darker();
        Color brighterResult8 = darkerResult3.brighter();
        assertEquals(-10187742, brighterResult8.getRGB());
        Color darkerResult4 = brighterResult7.darker();
        Color brighterResult9 = darkerResult4.brighter();
        assertEquals(-10187744, brighterResult9.getRGB());
        Color darkerResult5 = brighterResult8.darker();
        Color brighterResult10 = darkerResult5.brighter();
        assertEquals(-10187744, brighterResult10.getRGB());
        Color darkerResult6 = brighterResult10.darker();
        Color brighterResult11 = darkerResult6.brighter();
        assertEquals(-10187745, brighterResult11.getRGB());
        Color darkerResult7 = darkerResult5.darker();
        Color brighterResult12 = darkerResult7.brighter();
        Color brighterResult13 = brighterResult12.brighter();
        assertEquals(-10188257, brighterResult13.getRGB());
        Color darkerResult8 = darkerResult3.darker();
        Color brighterResult14 = darkerResult8.brighter();
        Color brighterResult15 = brighterResult14.brighter();
        assertEquals(-10188257, brighterResult15.getRGB());
        Color darkerResult9 = brighterResult2.darker();
        Color darkerResult10 = darkerResult9.darker();
        assertEquals(-10191838, darkerResult10.getRGB());
        Color darkerResult11 = darkerResult10.darker();
        Color brighterResult16 = darkerResult11.brighter();
        assertEquals(-10192352, brighterResult16.getRGB());
        Color brighterResult17 = darkerResult.brighter();
        Color darkerResult12 = brighterResult17.darker();
        assertEquals(-10253277, darkerResult12.getRGB());
        Color brighterResult18 = brighterResult7.brighter();
        Color darkerResult13 = brighterResult18.darker();
        assertEquals(-10253279, darkerResult13.getRGB());
        Color brighterResult19 = brighterResult8.brighter();
        Color darkerResult14 = brighterResult19.darker();
        assertEquals(-10253279, darkerResult14.getRGB());
        Color brighterResult20 = brighterResult10.brighter();
        Color darkerResult15 = brighterResult20.darker();
        assertEquals(-10253281, darkerResult15.getRGB());
        Color brighterResult21 = darkerResult9.brighter();
        Color darkerResult16 = brighterResult21.darker();
        Color darkerResult17 = darkerResult16.darker();
        assertEquals(-10257630, darkerResult17.getRGB());
        Color brighterResult22 = darkerResult10.brighter();
        Color darkerResult18 = brighterResult22.darker();
        assertEquals(-10257631, darkerResult18.getRGB());
        Color brighterResult23 = darkerResult12.brighter();
        Color darkerResult19 = brighterResult23.darker();
        assertEquals(-10318813, darkerResult19.getRGB());
        Color darkerResult20 = darkerResult14.darker();
        Color brighterResult24 = darkerResult20.brighter();
        assertEquals(-10318816, brighterResult24.getRGB());
        Color brighterResult25 = darkerResult14.brighter();
        Color darkerResult21 = brighterResult25.darker();
        assertEquals(-10318816, darkerResult21.getRGB());
        Color brighterResult26 = brighterResult19.brighter();
        Color darkerResult22 = brighterResult26.darker();
        Color darkerResult23 = darkerResult22.darker();
        assertEquals(-10322912, darkerResult23.getRGB());
        Color darkerResult24 = darkerResult8.darker();
        Color brighterResult27 = darkerResult24.brighter();
        Color brighterResult28 = brighterResult27.brighter();
        Color brighterResult29 = brighterResult28.brighter();
        assertEquals(-10385634, brighterResult29.getRGB());
        Color darkerResult25 = brighterResult3.darker();
        Color darkerResult26 = darkerResult25.darker();
        Color darkerResult27 = darkerResult26.darker();
        assertEquals(-11119070, darkerResult27.getRGB());
        assertEquals(-112, brighterResult4.getRGB());
        Color brighterResult30 = brighterResult21.brighter();
        Color brighterResult31 = brighterResult30.brighter();
        assertEquals(-114, brighterResult31.getRGB());
        Color brighterResult32 = darkerResult25.brighter();
        Color brighterResult33 = brighterResult32.brighter();
        assertEquals(-114, brighterResult33.getRGB());
        Color brighterResult34 = brighterResult26.brighter();
        Color brighterResult35 = brighterResult34.brighter();
        assertEquals(-118, brighterResult35.getRGB());
        assertEquals(-12164584, darkerResult2.getRGB());
        assertEquals(-12164584, darkerResult3.getRGB());
        assertEquals(-12164585, darkerResult4.getRGB());
        assertEquals(-12164585, darkerResult5.getRGB());
        assertEquals(-12164586, darkerResult6.getRGB());
        assertEquals(-12164842, brighterResult12.getRGB());
        Color darkerResult28 = darkerResult2.darker();
        Color brighterResult36 = darkerResult28.brighter();
        assertEquals(-12164842, brighterResult36.getRGB());
        assertEquals(-12164842, brighterResult14.getRGB());
        Color darkerResult29 = brighterResult15.darker();
        assertEquals(-12165099, darkerResult29.getRGB());
        Color darkerResult30 = brighterResult14.darker();
        Color brighterResult37 = darkerResult30.brighter();
        assertEquals(-12165355, brighterResult37.getRGB());
        assertEquals(-12167657, darkerResult11.getRGB());
        Color darkerResult31 = darkerResult12.darker();
        assertEquals(-12230120, darkerResult31.getRGB());
        assertEquals(-12230121, darkerResult20.getRGB());
        assertEquals(-12296427, brighterResult28.getRGB());
        Color darkerResult32 = darkerResult4.darker();
        assertEquals(-13548528, darkerResult32.getRGB());
        assertEquals(-13548528, darkerResult7.getRGB());
        assertEquals(-13548528, darkerResult28.getRGB());
        assertEquals(-13548528, darkerResult8.getRGB());
        Color darkerResult33 = darkerResult6.darker();
        assertEquals(-13548529, darkerResult33.getRGB());
        Color darkerResult34 = brighterResult12.darker();
        assertEquals(-13548785, darkerResult34.getRGB());
        assertEquals(-13548785, darkerResult30.getRGB());
        Color darkerResult35 = darkerResult11.darker();
        assertEquals(-13550576, darkerResult35.getRGB());
        Color darkerResult36 = darkerResult20.darker();
        assertEquals(-13614064, darkerResult36.getRGB());
        Color darkerResult37 = darkerResult7.darker();
        Color brighterResult38 = darkerResult37.brighter();
        assertEquals(-13614321, brighterResult38.getRGB());
        assertEquals(-13614321, brighterResult27.getRGB());
        Color darkerResult38 = brighterResult28.darker();
        assertEquals(-13680114, darkerResult38.getRGB());
        Color darkerResult39 = brighterResult27.darker();
        Color brighterResult39 = darkerResult39.brighter();
        assertEquals(-13680370, brighterResult39.getRGB());
        Color darkerResult40 = darkerResult24.darker();
        Color brighterResult40 = darkerResult40.brighter();
        Color brighterResult41 = brighterResult40.brighter();
        assertEquals(-13811698, brighterResult41.getRGB());
        assertEquals(-14536949, darkerResult37.getRGB());
        Color darkerResult41 = darkerResult28.darker();
        assertEquals(-14536949, darkerResult41.getRGB());
        assertEquals(-14536949, darkerResult24.getRGB());
        Color darkerResult42 = darkerResult30.darker();
        assertEquals(-14537206, darkerResult42.getRGB());
        assertEquals(-14602742, darkerResult39.getRGB());
        assertEquals(-14668534, brighterResult40.getRGB());
        Color darkerResult43 = darkerResult39.darker();
        assertEquals(-15261689, darkerResult43.getRGB());
        Color darkerResult44 = darkerResult37.darker();
        assertEquals(-15261689, darkerResult44.getRGB());
        assertEquals(-15261689, darkerResult40.getRGB());
        Color darkerResult45 = brighterResult40.darker();
        assertEquals(-15327481, darkerResult45.getRGB());
        Color darkerResult46 = darkerResult40.darker();
        Color brighterResult42 = darkerResult46.brighter();
        assertEquals(-15327483, brighterResult42.getRGB());
        Color brighterResult43 = brighterResult17.brighter();
        Color brighterResult44 = brighterResult43.brighter();
        assertEquals(-155, brighterResult44.getRGB());
        assertEquals(-155, brighterResult3.getRGB());
        assertEquals(-156, brighterResult30.getRGB());
        assertEquals(-15723004, darkerResult46.getRGB());
        assertEquals(-159, brighterResult34.getRGB());
        Color darkerResult47 = darkerResult46.darker();
        assertEquals(-16052478, darkerResult47.getRGB());
        assertEquals(-3276985, brighterResult2.getRGB());
        assertEquals(-3342778, brighterResult21.getRGB());
        assertEquals(-3473593, brighterResult43.getRGB());
        Color brighterResult45 = brighterResult18.brighter();
        assertEquals(-3473596, brighterResult45.getRGB());
        assertEquals(-3473596, brighterResult26.getRGB());
        Color brighterResult46 = brighterResult20.brighter();
        assertEquals(-3473600, brighterResult46.getRGB());
        Color brighterResult47 = darkerResult16.brighter();
        assertEquals(-3474362, brighterResult47.getRGB());
        Color brighterResult48 = brighterResult22.brighter();
        assertEquals(-3474364, brighterResult48.getRGB());
        Color brighterResult49 = brighterResult23.brighter();
        assertEquals(-3539129, brighterResult49.getRGB());
        Color brighterResult50 = brighterResult25.brighter();
        assertEquals(-3539133, brighterResult50.getRGB());
        Color brighterResult51 = darkerResult22.brighter();
        assertEquals(-3539389, brighterResult51.getRGB());
        Color darkerResult48 = brighterResult5.darker();
        assertEquals(-5066097, darkerResult48.getRGB());
        Color darkerResult49 = brighterResult4.darker();
        assertEquals(-5066140, darkerResult49.getRGB());
        assertEquals(-5066170, darkerResult25.getRGB());
        Color darkerResult50 = brighterResult30.darker();
        assertEquals(-5066170, darkerResult50.getRGB());
        Color darkerResult51 = brighterResult34.darker();
        assertEquals(-5066173, darkerResult51.getRGB());
        assertEquals(-51, brighterResult5.getRGB());
        Color brighterResult52 = darkerResult26.brighter();
        assertEquals(-5131962, brighterResult52.getRGB());
        Color darkerResult52 = brighterResult32.darker();
        assertEquals(-5131962, darkerResult52.getRGB());
        Color brighterResult53 = darkerResult49.brighter();
        assertEquals(-65906, brighterResult53.getRGB());
        assertEquals(-65948, brighterResult32.getRGB());
        assertEquals(-7288782, brighterResult.getRGB());
        assertEquals(-7359951, darkerResult9.getRGB());
        assertEquals(-7419854, brighterResult17.getRGB());
        assertEquals(-7419856, brighterResult18.getRGB());
        assertEquals(-7419856, brighterResult19.getRGB());
        assertEquals(-7419859, brighterResult20.getRGB());
        Color brighterResult54 = brighterResult15.brighter();
        assertEquals(-7420628, brighterResult54.getRGB());
        assertEquals(-7425743, darkerResult16.getRGB());
        assertEquals(-7425744, brighterResult22.getRGB());
        assertEquals(-7485390, brighterResult23.getRGB());
        assertEquals(-7485393, brighterResult25.getRGB());
        Color darkerResult53 = brighterResult43.darker();
        assertEquals(-7491023, darkerResult53.getRGB());
        assertEquals(-7491025, darkerResult22.getRGB());
        assertEquals(-8618959, darkerResult26.getRGB());
        assertEquals(0, tile2.getCaveCoinCount());
        assertEquals(1, brighterResult6.getTransparency());
        assertEquals(1, brighterResult35.getTransparency());
        assertEquals(1, brighterResult5.getTransparency());
        assertEquals(1, brighterResult34.getTransparency());
        assertEquals(1, brighterResult4.getTransparency());
        assertEquals(1, brighterResult31.getTransparency());
        assertEquals(1, brighterResult46.getTransparency());
        assertEquals(1, brighterResult44.getTransparency());
        assertEquals(1, brighterResult45.getTransparency());
        assertEquals(1, brighterResult29.getTransparency());
        assertEquals(1, brighterResult54.getTransparency());
        assertEquals(1, brighterResult26.getTransparency());
        assertEquals(1, brighterResult3.getTransparency());
        assertEquals(1, brighterResult33.getTransparency());
        assertEquals(1, brighterResult50.getTransparency());
        assertEquals(1, brighterResult30.getTransparency());
        assertEquals(1, brighterResult49.getTransparency());
        assertEquals(1, brighterResult20.getTransparency());
        assertEquals(1, brighterResult43.getTransparency());
        assertEquals(1, brighterResult48.getTransparency());
        assertEquals(1, brighterResult13.getTransparency());
        assertEquals(1, brighterResult18.getTransparency());
        assertEquals(1, brighterResult41.getTransparency());
        assertEquals(1, brighterResult28.getTransparency());
        assertEquals(1, brighterResult15.getTransparency());
        assertEquals(1, brighterResult19.getTransparency());
        assertEquals(1, brighterResult2.getTransparency());
        assertEquals(1, brighterResult53.getTransparency());
        assertEquals(1, brighterResult51.getTransparency());
        assertEquals(1, brighterResult32.getTransparency());
        assertEquals(1, brighterResult25.getTransparency());
        assertEquals(1, brighterResult21.getTransparency());
        assertEquals(1, brighterResult47.getTransparency());
        assertEquals(1, brighterResult11.getTransparency());
        assertEquals(1, brighterResult23.getTransparency());
        assertEquals(1, brighterResult9.getTransparency());
        assertEquals(1, brighterResult39.getTransparency());
        assertEquals(1, brighterResult37.getTransparency());
        assertEquals(1, brighterResult10.getTransparency());
        assertEquals(1, brighterResult17.getTransparency());
        assertEquals(1, brighterResult52.getTransparency());
        assertEquals(1, brighterResult24.getTransparency());
        assertEquals(1, brighterResult22.getTransparency());
        assertEquals(1, brighterResult12.getTransparency());
        assertEquals(1, brighterResult7.getTransparency());
        assertEquals(1, brighterResult16.getTransparency());
        assertEquals(1, brighterResult38.getTransparency());
        assertEquals(1, brighterResult36.getTransparency());
        assertEquals(1, brighterResult42.getTransparency());
        assertEquals(1, brighterResult40.getTransparency());
        assertEquals(1, brighterResult27.getTransparency());
        assertEquals(1, brighterResult14.getTransparency());
        assertEquals(1, brighterResult8.getTransparency());
        assertEquals(1, brighterResult.getTransparency());
        assertEquals(1, darkerResult48.getTransparency());
        assertEquals(1, darkerResult51.getTransparency());
        assertEquals(1, darkerResult49.getTransparency());
        assertEquals(1, darkerResult22.getTransparency());
        assertEquals(1, darkerResult25.getTransparency());
        assertEquals(1, darkerResult50.getTransparency());
        assertEquals(1, darkerResult15.getTransparency());
        assertEquals(1, darkerResult53.getTransparency());
        assertEquals(1, darkerResult13.getTransparency());
        assertEquals(1, darkerResult38.getTransparency());
        assertEquals(1, darkerResult29.getTransparency());
        assertEquals(1, darkerResult14.getTransparency());
        assertEquals(1, darkerResult9.getTransparency());
        assertEquals(1, darkerResult52.getTransparency());
        assertEquals(1, darkerResult21.getTransparency());
        assertEquals(1, darkerResult16.getTransparency());
        assertEquals(1, darkerResult19.getTransparency());
        assertEquals(1, darkerResult6.getTransparency());
        assertEquals(1, darkerResult12.getTransparency());
        assertEquals(1, darkerResult18.getTransparency());
        assertEquals(1, darkerResult34.getTransparency());
        assertEquals(1, darkerResult4.getTransparency());
        assertEquals(1, darkerResult45.getTransparency());
        assertEquals(1, darkerResult39.getTransparency());
        assertEquals(1, darkerResult30.getTransparency());
        assertEquals(1, darkerResult5.getTransparency());
        assertEquals(1, darkerResult.getTransparency());
        assertEquals(1, darkerResult23.getTransparency());
        assertEquals(1, darkerResult26.getTransparency());
        assertEquals(1, darkerResult20.getTransparency());
        assertEquals(1, darkerResult10.getTransparency());
        assertEquals(1, darkerResult17.getTransparency());
        assertEquals(1, darkerResult33.getTransparency());
        assertEquals(1, darkerResult31.getTransparency());
        assertEquals(1, darkerResult32.getTransparency());
        assertEquals(1, darkerResult43.getTransparency());
        assertEquals(1, darkerResult42.getTransparency());
        assertEquals(1, darkerResult7.getTransparency());
        assertEquals(1, darkerResult2.getTransparency());
        assertEquals(1, darkerResult27.getTransparency());
        assertEquals(1, darkerResult36.getTransparency());
        assertEquals(1, darkerResult11.getTransparency());
        assertEquals(1, darkerResult37.getTransparency());
        assertEquals(1, darkerResult28.getTransparency());
        assertEquals(1, darkerResult35.getTransparency());
        assertEquals(1, darkerResult44.getTransparency());
        assertEquals(1, darkerResult41.getTransparency());
        assertEquals(1, darkerResult47.getTransparency());
        assertEquals(1, darkerResult46.getTransparency());
        assertEquals(1, darkerResult40.getTransparency());
        assertEquals(1, darkerResult24.getTransparency());
        assertEquals(1, darkerResult8.getTransparency());
        assertEquals(1, darkerResult3.getTransparency());
        assertEquals(1, tileColor.getTransparency());
        assertEquals(1, tile2.getPower());
        assertEquals(1, tile2.getQ());
        assertEquals(1, tile2.getR());
        assertEquals(10, brighterResult40.getBlue());
        assertEquals(10, darkerResult39.getBlue());
        assertEquals(10, darkerResult42.getBlue());
        assertEquals(100, brighterResult30.getBlue());
        assertEquals(100, brighterResult32.getBlue());
        assertEquals(100, darkerResult49.getBlue());
        assertEquals(100, brighterResult13.getRed());
        assertEquals(100, brighterResult15.getRed());
        assertEquals(100, brighterResult11.getRed());
        assertEquals(100, brighterResult9.getRed());
        assertEquals(100, brighterResult10.getRed());
        assertEquals(100, brighterResult7.getRed());
        assertEquals(100, brighterResult16.getRed());
        assertEquals(100, brighterResult8.getRed());
        assertEquals(100, darkerResult.getRed());
        assertEquals(100, darkerResult10.getRed());
        assertEquals(101, brighterResult44.getBlue());
        assertEquals(101, brighterResult3.getBlue());
        assertEquals(101, tileColor.getRed());
        assertEquals(11, darkerResult37.getBlue());
        assertEquals(11, darkerResult41.getBlue());
        assertEquals(11, darkerResult24.getBlue());
        assertEquals(11, darkerResult47.getRed());
        assertEquals(122, brighterResult16.getGreen());
        assertEquals(123, darkerResult18.getGreen());
        assertEquals(123, darkerResult17.getGreen());
        assertEquals(124, darkerResult23.getGreen());
        assertEquals(124, darkerResult26.getGreen());
        assertEquals(124, darkerResult10.getGreen());
        assertEquals(124, darkerResult26.getRed());
        assertEquals(135, brighterResult29.getGreen());
        assertEquals(138, brighterResult35.getBlue());
        assertEquals(138, brighterResult13.getGreen());
        Color brighterResult55 = brighterResult36.brighter();
        assertEquals(138, brighterResult55.getGreen());
        assertEquals(138, brighterResult15.getGreen());
        assertEquals(14, brighterResult41.getBlue());
        assertEquals(14, brighterResult39.getBlue());
        assertEquals(14, darkerResult38.getBlue());
        assertEquals(140, brighterResult11.getGreen());
        assertEquals(140, brighterResult9.getGreen());
        assertEquals(140, brighterResult10.getGreen());
        assertEquals(140, brighterResult24.getGreen());
        assertEquals(140, brighterResult7.getGreen());
        assertEquals(140, brighterResult8.getGreen());
        assertEquals(140, darkerResult15.getGreen());
        assertEquals(140, darkerResult13.getGreen());
        assertEquals(140, darkerResult14.getGreen());
        assertEquals(140, darkerResult21.getGreen());
        assertEquals(140, darkerResult19.getGreen());
        assertEquals(140, darkerResult12.getGreen());
        assertEquals(140, darkerResult.getGreen());
        assertEquals(140, tileColor.getGreen());
        assertEquals(141, brighterResult25.getRed());
        assertEquals(141, brighterResult23.getRed());
        assertEquals(141, darkerResult22.getRed());
        assertEquals(141, darkerResult53.getRed());
        assertEquals(142, brighterResult31.getBlue());
        assertEquals(142, brighterResult33.getBlue());
        assertEquals(142, brighterResult53.getBlue());
        assertEquals(142, brighterResult54.getRed());
        assertEquals(142, brighterResult20.getRed());
        assertEquals(142, brighterResult18.getRed());
        assertEquals(142, brighterResult19.getRed());
        assertEquals(142, brighterResult17.getRed());
        assertEquals(142, brighterResult22.getRed());
        assertEquals(142, darkerResult16.getRed());
        assertEquals(143, darkerResult48.getBlue());
        assertEquals(143, darkerResult9.getRed());
        assertEquals(144, brighterResult4.getBlue());
        assertEquals(144, brighterResult.getRed());
        assertEquals(15, brighterResult38.getBlue());
        assertEquals(15, brighterResult27.getBlue());
        assertEquals(15, darkerResult34.getBlue());
        assertEquals(15, darkerResult30.getBlue());
        assertEquals(15, darkerResult33.getBlue());
        assertEquals(15, darkerResult47.getGreen());
        assertEquals(177, brighterResult52.getGreen());
        assertEquals(177, brighterResult22.getGreen());
        assertEquals(177, darkerResult52.getGreen());
        assertEquals(177, darkerResult16.getGreen());
        assertEquals(177, brighterResult52.getRed());
        assertEquals(177, darkerResult52.getRed());
        assertEquals(178, darkerResult48.getGreen());
        assertEquals(178, darkerResult51.getGreen());
        assertEquals(178, darkerResult49.getGreen());
        assertEquals(178, darkerResult22.getGreen());
        assertEquals(178, darkerResult25.getGreen());
        assertEquals(178, darkerResult50.getGreen());
        assertEquals(178, darkerResult53.getGreen());
        assertEquals(178, darkerResult9.getGreen());
        assertEquals(178, darkerResult48.getRed());
        assertEquals(178, darkerResult51.getRed());
        assertEquals(178, darkerResult49.getRed());
        assertEquals(178, darkerResult25.getRed());
        assertEquals(178, darkerResult50.getRed());
        assertEquals(197, brighterResult54.getGreen());
        assertEquals(2, darkerResult47.getBlue());
        assertEquals(200, brighterResult20.getGreen());
        assertEquals(200, brighterResult18.getGreen());
        assertEquals(200, brighterResult19.getGreen());
        assertEquals(200, brighterResult25.getGreen());
        assertEquals(200, brighterResult23.getGreen());
        assertEquals(200, brighterResult17.getGreen());
        assertEquals(200, brighterResult.getGreen());
        assertEquals(201, brighterResult50.getRed());
        assertEquals(201, brighterResult49.getRed());
        assertEquals(201, brighterResult51.getRed());
        assertEquals(202, brighterResult46.getRed());
        assertEquals(202, brighterResult45.getRed());
        assertEquals(202, brighterResult26.getRed());
        assertEquals(202, brighterResult43.getRed());
        assertEquals(202, brighterResult48.getRed());
        assertEquals(202, brighterResult47.getRed());
        assertEquals(204, brighterResult21.getRed());
        assertEquals(205, brighterResult5.getBlue());
        assertEquals(205, brighterResult2.getRed());
        assertEquals(21, brighterResult28.getBlue());
        assertEquals(21, brighterResult37.getBlue());
        assertEquals(21, darkerResult29.getBlue());
        assertEquals(22, brighterResult12.getBlue());
        assertEquals(22, brighterResult36.getBlue());
        assertEquals(22, brighterResult14.getBlue());
        assertEquals(22, darkerResult6.getBlue());
        assertEquals(22, darkerResult46.getGreen());
        assertEquals(22, brighterResult42.getRed());
        assertEquals(22, darkerResult45.getRed());
        assertEquals(23, darkerResult4.getBlue());
        assertEquals(23, darkerResult5.getBlue());
        assertEquals(23, darkerResult20.getBlue());
        assertEquals(23, darkerResult11.getBlue());
        assertEquals(23, darkerResult43.getRed());
        assertEquals(23, darkerResult44.getRed());
        assertEquals(23, darkerResult40.getRed());
        assertEquals(252, brighterResult48.getGreen());
        assertEquals(252, brighterResult47.getGreen());
        assertEquals(254, brighterResult53.getGreen());
        assertEquals(254, brighterResult51.getGreen());
        assertEquals(254, brighterResult32.getGreen());
        assertEquals(254, brighterResult21.getGreen());
        assertEquals(254, brighterResult53.getRed());
        assertEquals(254, brighterResult32.getRed());
        assertEquals(255, brighterResult6.getAlpha());
        assertEquals(255, brighterResult35.getAlpha());
        assertEquals(255, brighterResult5.getAlpha());
        assertEquals(255, brighterResult34.getAlpha());
        assertEquals(255, brighterResult4.getAlpha());
        assertEquals(255, brighterResult31.getAlpha());
        assertEquals(255, brighterResult46.getAlpha());
        assertEquals(255, brighterResult44.getAlpha());
        assertEquals(255, brighterResult45.getAlpha());
        assertEquals(255, brighterResult29.getAlpha());
        assertEquals(255, brighterResult54.getAlpha());
        assertEquals(255, brighterResult26.getAlpha());
        assertEquals(255, brighterResult3.getAlpha());
        assertEquals(255, brighterResult33.getAlpha());
        assertEquals(255, brighterResult50.getAlpha());
        assertEquals(255, brighterResult30.getAlpha());
        assertEquals(255, brighterResult49.getAlpha());
        assertEquals(255, brighterResult20.getAlpha());
        assertEquals(255, brighterResult43.getAlpha());
        assertEquals(255, brighterResult48.getAlpha());
        assertEquals(255, brighterResult13.getAlpha());
        assertEquals(255, brighterResult18.getAlpha());
        assertEquals(255, brighterResult55.getAlpha());
        assertEquals(255, brighterResult41.getAlpha());
        assertEquals(255, brighterResult28.getAlpha());
        assertEquals(255, brighterResult15.getAlpha());
        assertEquals(255, brighterResult19.getAlpha());
        assertEquals(255, brighterResult2.getAlpha());
        assertEquals(255, brighterResult53.getAlpha());
        assertEquals(255, brighterResult51.getAlpha());
        assertEquals(255, brighterResult32.getAlpha());
        assertEquals(255, brighterResult25.getAlpha());
        assertEquals(255, brighterResult21.getAlpha());
        assertEquals(255, brighterResult47.getAlpha());
        assertEquals(255, brighterResult11.getAlpha());
        assertEquals(255, brighterResult23.getAlpha());
        assertEquals(255, brighterResult9.getAlpha());
        assertEquals(255, brighterResult39.getAlpha());
        assertEquals(255, brighterResult37.getAlpha());
        assertEquals(255, brighterResult10.getAlpha());
        assertEquals(255, brighterResult17.getAlpha());
        assertEquals(255, brighterResult52.getAlpha());
        assertEquals(255, brighterResult24.getAlpha());
        assertEquals(255, brighterResult22.getAlpha());
        assertEquals(255, brighterResult12.getAlpha());
        assertEquals(255, brighterResult7.getAlpha());
        assertEquals(255, brighterResult16.getAlpha());
        assertEquals(255, brighterResult38.getAlpha());
        assertEquals(255, brighterResult36.getAlpha());
        assertEquals(255, brighterResult42.getAlpha());
        assertEquals(255, brighterResult40.getAlpha());
        assertEquals(255, brighterResult27.getAlpha());
        assertEquals(255, brighterResult14.getAlpha());
        assertEquals(255, brighterResult8.getAlpha());
        assertEquals(255, brighterResult.getAlpha());
        assertEquals(255, darkerResult48.getAlpha());
        assertEquals(255, darkerResult51.getAlpha());
        assertEquals(255, darkerResult49.getAlpha());
        assertEquals(255, darkerResult22.getAlpha());
        assertEquals(255, darkerResult25.getAlpha());
        assertEquals(255, darkerResult50.getAlpha());
        assertEquals(255, darkerResult15.getAlpha());
        assertEquals(255, darkerResult53.getAlpha());
        assertEquals(255, darkerResult13.getAlpha());
        assertEquals(255, darkerResult38.getAlpha());
        assertEquals(255, darkerResult29.getAlpha());
        assertEquals(255, darkerResult14.getAlpha());
        assertEquals(255, darkerResult9.getAlpha());
        assertEquals(255, darkerResult52.getAlpha());
        assertEquals(255, darkerResult21.getAlpha());
        assertEquals(255, darkerResult16.getAlpha());
        assertEquals(255, darkerResult19.getAlpha());
        assertEquals(255, darkerResult6.getAlpha());
        assertEquals(255, darkerResult12.getAlpha());
        assertEquals(255, darkerResult18.getAlpha());
        assertEquals(255, darkerResult34.getAlpha());
        assertEquals(255, darkerResult4.getAlpha());
        assertEquals(255, darkerResult45.getAlpha());
        assertEquals(255, darkerResult39.getAlpha());
        assertEquals(255, darkerResult30.getAlpha());
        assertEquals(255, darkerResult5.getAlpha());
        assertEquals(255, darkerResult.getAlpha());
        assertEquals(255, darkerResult23.getAlpha());
        assertEquals(255, darkerResult26.getAlpha());
        assertEquals(255, darkerResult20.getAlpha());
        assertEquals(255, darkerResult10.getAlpha());
        assertEquals(255, darkerResult17.getAlpha());
        assertEquals(255, darkerResult33.getAlpha());
        assertEquals(255, darkerResult31.getAlpha());
        assertEquals(255, darkerResult32.getAlpha());
        assertEquals(255, darkerResult43.getAlpha());
        assertEquals(255, darkerResult42.getAlpha());
        assertEquals(255, darkerResult7.getAlpha());
        assertEquals(255, darkerResult2.getAlpha());
        assertEquals(255, darkerResult27.getAlpha());
        assertEquals(255, darkerResult36.getAlpha());
        assertEquals(255, darkerResult11.getAlpha());
        assertEquals(255, darkerResult37.getAlpha());
        assertEquals(255, darkerResult28.getAlpha());
        assertEquals(255, darkerResult35.getAlpha());
        assertEquals(255, darkerResult44.getAlpha());
        assertEquals(255, darkerResult41.getAlpha());
        assertEquals(255, darkerResult47.getAlpha());
        assertEquals(255, darkerResult46.getAlpha());
        assertEquals(255, darkerResult40.getAlpha());
        assertEquals(255, darkerResult24.getAlpha());
        assertEquals(255, darkerResult8.getAlpha());
        assertEquals(255, darkerResult3.getAlpha());
        assertEquals(255, tileColor.getAlpha());
        assertEquals(255, brighterResult6.getBlue());
        assertEquals(255, brighterResult6.getGreen());
        assertEquals(255, brighterResult35.getGreen());
        assertEquals(255, brighterResult5.getGreen());
        assertEquals(255, brighterResult34.getGreen());
        assertEquals(255, brighterResult4.getGreen());
        assertEquals(255, brighterResult31.getGreen());
        assertEquals(255, brighterResult46.getGreen());
        assertEquals(255, brighterResult44.getGreen());
        assertEquals(255, brighterResult45.getGreen());
        assertEquals(255, brighterResult26.getGreen());
        assertEquals(255, brighterResult3.getGreen());
        assertEquals(255, brighterResult33.getGreen());
        assertEquals(255, brighterResult50.getGreen());
        assertEquals(255, brighterResult30.getGreen());
        assertEquals(255, brighterResult49.getGreen());
        assertEquals(255, brighterResult43.getGreen());
        assertEquals(255, brighterResult2.getGreen());
        assertEquals(255, brighterResult6.getRed());
        assertEquals(255, brighterResult35.getRed());
        assertEquals(255, brighterResult5.getRed());
        assertEquals(255, brighterResult34.getRed());
        assertEquals(255, brighterResult4.getRed());
        assertEquals(255, brighterResult31.getRed());
        assertEquals(255, brighterResult44.getRed());
        assertEquals(255, brighterResult3.getRed());
        assertEquals(255, brighterResult33.getRed());
        assertEquals(255, brighterResult30.getRed());
        ColorSpace colorSpace = tileColor.getColorSpace();
        assertEquals(3, colorSpace.getNumComponents());
        assertEquals(30, brighterResult29.getBlue());
        assertEquals(31, brighterResult13.getBlue());
        assertEquals(31, brighterResult55.getBlue());
        assertEquals(31, brighterResult15.getBlue());
        assertEquals(31, brighterResult11.getBlue());
        assertEquals(31, darkerResult15.getBlue());
        assertEquals(31, brighterResult42.getGreen());
        assertEquals(31, darkerResult45.getGreen());
        assertEquals(33, darkerResult13.getBlue());
        assertEquals(33, darkerResult14.getBlue());
        assertEquals(33, darkerResult18.getBlue());
        assertEquals(33, darkerResult39.getRed());
        assertEquals(34, brighterResult7.getBlue());
        assertEquals(34, brighterResult8.getBlue());
        assertEquals(34, darkerResult10.getBlue());
        assertEquals(34, darkerResult17.getBlue());
        assertEquals(34, darkerResult27.getBlue());
        assertEquals(34, darkerResult42.getRed());
        assertEquals(34, darkerResult37.getRed());
        assertEquals(34, darkerResult41.getRed());
        assertEquals(34, darkerResult24.getRed());
        assertEquals(35, darkerResult19.getBlue());
        assertEquals(35, darkerResult12.getBlue());
        assertEquals(35, darkerResult.getBlue());
        assertEquals(35, tileColor.getBlue());
        assertEquals(4, darkerResult46.getBlue());
        assertEquals(44, brighterResult54.getBlue());
        assertEquals(45, brighterResult20.getBlue());
        assertEquals(45, brighterResult40.getGreen());
        assertEquals(45, brighterResult41.getRed());
        assertEquals(46, darkerResult39.getGreen());
        assertEquals(46, darkerResult42.getGreen());
        assertEquals(47, brighterResult25.getBlue());
        assertEquals(47, darkerResult22.getBlue());
        assertEquals(47, darkerResult37.getGreen());
        assertEquals(47, darkerResult41.getGreen());
        assertEquals(47, darkerResult24.getGreen());
        assertEquals(47, brighterResult39.getRed());
        assertEquals(47, darkerResult38.getRed());
        assertEquals(48, brighterResult18.getBlue());
        assertEquals(48, brighterResult19.getBlue());
        assertEquals(48, brighterResult22.getBlue());
        assertEquals(48, brighterResult38.getRed());
        assertEquals(48, brighterResult27.getRed());
        assertEquals(48, darkerResult36.getRed());
        assertEquals(49, darkerResult53.getBlue());
        assertEquals(49, darkerResult9.getBlue());
        assertEquals(49, darkerResult16.getBlue());
        assertEquals(49, darkerResult26.getBlue());
        assertEquals(49, darkerResult34.getRed());
        assertEquals(49, darkerResult30.getRed());
        assertEquals(49, darkerResult33.getRed());
        assertEquals(49, darkerResult32.getRed());
        assertEquals(49, darkerResult7.getRed());
        assertEquals(49, darkerResult28.getRed());
        assertEquals(49, darkerResult35.getRed());
        assertEquals(49, darkerResult8.getRed());
        assertEquals(5, brighterResult42.getBlue());
        assertEquals(5, colorSpace.getType());
        assertEquals(50, brighterResult23.getBlue());
        assertEquals(50, brighterResult17.getBlue());
        assertEquals(50, brighterResult.getBlue());
        assertEquals(60, darkerResult35.getGreen());
        assertEquals(65, brighterResult39.getGreen());
        assertEquals(66, darkerResult38.getGreen());
        assertEquals(67, brighterResult50.getBlue());
        assertEquals(67, brighterResult51.getBlue());
        assertEquals(67, darkerResult51.getBlue());
        assertEquals(67, brighterResult38.getGreen());
        assertEquals(67, brighterResult27.getGreen());
        assertEquals(67, darkerResult34.getGreen());
        assertEquals(67, darkerResult30.getGreen());
        assertEquals(68, brighterResult45.getBlue());
        assertEquals(68, brighterResult26.getBlue());
        assertEquals(68, brighterResult48.getBlue());
        assertEquals(68, darkerResult33.getGreen());
        assertEquals(68, darkerResult32.getGreen());
        assertEquals(68, darkerResult7.getGreen());
        assertEquals(68, darkerResult36.getGreen());
        assertEquals(68, darkerResult28.getGreen());
        assertEquals(68, darkerResult8.getGreen());
        assertEquals(68, brighterResult28.getRed());
        assertEquals(69, darkerResult20.getRed());
        assertEquals(69, darkerResult31.getRed());
        assertEquals(7, darkerResult45.getBlue());
        assertEquals(7, darkerResult43.getBlue());
        assertEquals(7, darkerResult44.getBlue());
        assertEquals(7, darkerResult40.getBlue());
        assertEquals(70, brighterResult21.getBlue());
        assertEquals(70, brighterResult47.getBlue());
        assertEquals(70, brighterResult52.getBlue());
        assertEquals(70, darkerResult25.getBlue());
        assertEquals(70, darkerResult50.getBlue());
        assertEquals(70, darkerResult52.getBlue());
        assertEquals(70, brighterResult37.getRed());
        assertEquals(70, brighterResult12.getRed());
        assertEquals(70, brighterResult36.getRed());
        assertEquals(70, brighterResult14.getRed());
        assertEquals(70, darkerResult29.getRed());
        assertEquals(70, darkerResult6.getRed());
        assertEquals(70, darkerResult4.getRed());
        assertEquals(70, darkerResult5.getRed());
        assertEquals(70, darkerResult2.getRed());
        assertEquals(70, darkerResult11.getRed());
        assertEquals(70, darkerResult3.getRed());
        assertEquals(71, brighterResult49.getBlue());
        assertEquals(71, brighterResult43.getBlue());
        assertEquals(71, brighterResult2.getBlue());
        assertEquals(86, darkerResult27.getGreen());
        assertEquals(86, darkerResult11.getGreen());
        assertEquals(86, darkerResult27.getRed());
        assertEquals(95, brighterResult28.getGreen());
        assertEquals(95, brighterResult37.getGreen());
        assertEquals(96, darkerResult29.getGreen());
        assertEquals(97, brighterResult34.getBlue());
        assertEquals(97, brighterResult12.getGreen());
        assertEquals(97, brighterResult36.getGreen());
        assertEquals(97, brighterResult14.getGreen());
        assertEquals(97, brighterResult29.getRed());
        assertEquals(98, darkerResult6.getGreen());
        assertEquals(98, darkerResult4.getGreen());
        assertEquals(98, darkerResult5.getGreen());
        assertEquals(98, darkerResult20.getGreen());
        assertEquals(98, darkerResult31.getGreen());
        assertEquals(98, darkerResult2.getGreen());
        assertEquals(98, darkerResult3.getGreen());
        assertEquals(98, brighterResult24.getRed());
        assertEquals(98, darkerResult21.getRed());
        assertEquals(98, darkerResult19.getRed());
        assertEquals(98, darkerResult23.getRed());
        assertEquals(99, darkerResult15.getRed());
        assertEquals(99, darkerResult13.getRed());
        assertEquals(99, darkerResult14.getRed());
        assertEquals(99, darkerResult12.getRed());
        assertEquals(99, darkerResult18.getRed());
        assertEquals(99, darkerResult17.getRed());
        assertEquals(TileType.Machete, tile2.getTileType());
        assertFalse(tile2.hasCaveCoins());
        assertFalse(tile2.isBlockadeTile());
        assertFalse(tile2.isEndTile());
        assertFalse(tile2.isStartingTile());
        assertTrue(colorSpace.isCS_sRGB());
        assertTrue(tile2.getCaveCoins().isEmpty());
        assertTrue(tile2.getPlayers().isEmpty());
        assertTrue(tile2.isEmpty());
        assertTrue(tile2.isLastWaitingTile());
        assertEquals(Double.SIZE, brighterResult46.getBlue());
        assertEquals(Double.SIZE, brighterResult41.getGreen());
        assertEquals(Float.PRECISION, darkerResult31.getBlue());
        assertEquals(Float.PRECISION, darkerResult2.getBlue());
        assertEquals(Float.PRECISION, darkerResult3.getBlue());
        assertEquals(Integer.SIZE, brighterResult9.getBlue());
        assertEquals(Integer.SIZE, brighterResult10.getBlue());
        assertEquals(Integer.SIZE, brighterResult24.getBlue());
        assertEquals(Integer.SIZE, brighterResult16.getBlue());
        assertEquals(Integer.SIZE, darkerResult21.getBlue());
        assertEquals(Integer.SIZE, darkerResult23.getBlue());
        assertEquals(Integer.SIZE, darkerResult43.getGreen());
        assertEquals(Integer.SIZE, darkerResult44.getGreen());
        assertEquals(Integer.SIZE, darkerResult40.getGreen());
        assertEquals(Integer.SIZE, brighterResult40.getRed());
        assertEquals(Short.SIZE, darkerResult32.getBlue());
        assertEquals(Short.SIZE, darkerResult7.getBlue());
        assertEquals(Short.SIZE, darkerResult36.getBlue());
        assertEquals(Short.SIZE, darkerResult28.getBlue());
        assertEquals(Short.SIZE, darkerResult35.getBlue());
        assertEquals(Short.SIZE, darkerResult8.getBlue());
        assertEquals(Short.SIZE, darkerResult46.getRed());
        assertSame(tile, tile2);
        assertSame(tileView, actualTileController.getTileView());
        assertSame(colorSpace, brighterResult6.getColorSpace());
        assertSame(colorSpace, brighterResult35.getColorSpace());
        assertSame(colorSpace, brighterResult5.getColorSpace());
        assertSame(colorSpace, brighterResult34.getColorSpace());
        assertSame(colorSpace, brighterResult4.getColorSpace());
        assertSame(colorSpace, brighterResult31.getColorSpace());
        assertSame(colorSpace, brighterResult46.getColorSpace());
        assertSame(colorSpace, brighterResult44.getColorSpace());
        assertSame(colorSpace, brighterResult45.getColorSpace());
        assertSame(colorSpace, brighterResult29.getColorSpace());
        assertSame(colorSpace, brighterResult54.getColorSpace());
        assertSame(colorSpace, brighterResult26.getColorSpace());
        assertSame(colorSpace, brighterResult3.getColorSpace());
        assertSame(colorSpace, brighterResult33.getColorSpace());
        assertSame(colorSpace, brighterResult50.getColorSpace());
        assertSame(colorSpace, brighterResult30.getColorSpace());
        assertSame(colorSpace, brighterResult49.getColorSpace());
        assertSame(colorSpace, brighterResult20.getColorSpace());
        assertSame(colorSpace, brighterResult43.getColorSpace());
        assertSame(colorSpace, brighterResult48.getColorSpace());
        assertSame(colorSpace, brighterResult13.getColorSpace());
        assertSame(colorSpace, brighterResult18.getColorSpace());
        assertSame(colorSpace, brighterResult55.getColorSpace());
        assertSame(colorSpace, brighterResult41.getColorSpace());
        assertSame(colorSpace, brighterResult28.getColorSpace());
        assertSame(colorSpace, brighterResult15.getColorSpace());
        assertSame(colorSpace, brighterResult19.getColorSpace());
        assertSame(colorSpace, brighterResult2.getColorSpace());
        assertSame(colorSpace, brighterResult53.getColorSpace());
        assertSame(colorSpace, brighterResult51.getColorSpace());
        assertSame(colorSpace, brighterResult32.getColorSpace());
        assertSame(colorSpace, brighterResult25.getColorSpace());
        assertSame(colorSpace, brighterResult21.getColorSpace());
        assertSame(colorSpace, brighterResult47.getColorSpace());
        assertSame(colorSpace, brighterResult11.getColorSpace());
        assertSame(colorSpace, brighterResult23.getColorSpace());
        assertSame(colorSpace, brighterResult9.getColorSpace());
        assertSame(colorSpace, brighterResult39.getColorSpace());
        assertSame(colorSpace, brighterResult37.getColorSpace());
        assertSame(colorSpace, brighterResult10.getColorSpace());
        assertSame(colorSpace, brighterResult17.getColorSpace());
        assertSame(colorSpace, brighterResult52.getColorSpace());
        assertSame(colorSpace, brighterResult24.getColorSpace());
        assertSame(colorSpace, brighterResult22.getColorSpace());
        assertSame(colorSpace, brighterResult12.getColorSpace());
        assertSame(colorSpace, brighterResult7.getColorSpace());
        assertSame(colorSpace, brighterResult16.getColorSpace());
        assertSame(colorSpace, brighterResult38.getColorSpace());
        assertSame(colorSpace, brighterResult36.getColorSpace());
        assertSame(colorSpace, brighterResult42.getColorSpace());
        assertSame(colorSpace, brighterResult40.getColorSpace());
        assertSame(colorSpace, brighterResult27.getColorSpace());
        assertSame(colorSpace, brighterResult14.getColorSpace());
        assertSame(colorSpace, brighterResult8.getColorSpace());
        assertSame(colorSpace, brighterResult.getColorSpace());
        assertSame(colorSpace, darkerResult48.getColorSpace());
        assertSame(colorSpace, darkerResult51.getColorSpace());
        assertSame(colorSpace, darkerResult49.getColorSpace());
        assertSame(colorSpace, darkerResult22.getColorSpace());
        assertSame(colorSpace, darkerResult25.getColorSpace());
        assertSame(colorSpace, darkerResult50.getColorSpace());
        assertSame(colorSpace, darkerResult15.getColorSpace());
        assertSame(colorSpace, darkerResult53.getColorSpace());
        assertSame(colorSpace, darkerResult13.getColorSpace());
        assertSame(colorSpace, darkerResult38.getColorSpace());
        assertSame(colorSpace, darkerResult29.getColorSpace());
        assertSame(colorSpace, darkerResult14.getColorSpace());
        assertSame(colorSpace, darkerResult9.getColorSpace());
        assertSame(colorSpace, darkerResult52.getColorSpace());
        assertSame(colorSpace, darkerResult21.getColorSpace());
        assertSame(colorSpace, darkerResult16.getColorSpace());
        assertSame(colorSpace, darkerResult19.getColorSpace());
        assertSame(colorSpace, darkerResult6.getColorSpace());
        assertSame(colorSpace, darkerResult12.getColorSpace());
        assertSame(colorSpace, darkerResult18.getColorSpace());
        assertSame(colorSpace, darkerResult34.getColorSpace());
        assertSame(colorSpace, darkerResult4.getColorSpace());
        assertSame(colorSpace, darkerResult45.getColorSpace());
        assertSame(colorSpace, darkerResult39.getColorSpace());
        assertSame(colorSpace, darkerResult30.getColorSpace());
        assertSame(colorSpace, darkerResult5.getColorSpace());
        assertSame(colorSpace, darkerResult.getColorSpace());
        assertSame(colorSpace, darkerResult23.getColorSpace());
        assertSame(colorSpace, darkerResult26.getColorSpace());
        assertSame(colorSpace, darkerResult20.getColorSpace());
        assertSame(colorSpace, darkerResult10.getColorSpace());
        assertSame(colorSpace, darkerResult17.getColorSpace());
        assertSame(colorSpace, darkerResult33.getColorSpace());
        assertSame(colorSpace, darkerResult31.getColorSpace());
        assertSame(colorSpace, darkerResult32.getColorSpace());
        assertSame(colorSpace, darkerResult43.getColorSpace());
        assertSame(colorSpace, darkerResult42.getColorSpace());
        assertSame(colorSpace, darkerResult7.getColorSpace());
        assertSame(colorSpace, darkerResult2.getColorSpace());
        assertSame(colorSpace, darkerResult27.getColorSpace());
        assertSame(colorSpace, darkerResult36.getColorSpace());
        assertSame(colorSpace, darkerResult11.getColorSpace());
        assertSame(colorSpace, darkerResult37.getColorSpace());
        assertSame(colorSpace, darkerResult28.getColorSpace());
        assertSame(colorSpace, darkerResult35.getColorSpace());
        assertSame(colorSpace, darkerResult44.getColorSpace());
        assertSame(colorSpace, darkerResult41.getColorSpace());
        assertSame(colorSpace, darkerResult47.getColorSpace());
        assertSame(colorSpace, darkerResult46.getColorSpace());
        assertSame(colorSpace, darkerResult40.getColorSpace());
        assertSame(colorSpace, darkerResult24.getColorSpace());
        assertSame(colorSpace, darkerResult8.getColorSpace());
        assertSame(colorSpace, darkerResult3.getColorSpace());
    }

    /**
     * Method under test:
     * {@link TileController#updateView(Graphics2D, int, int, boolean, TileImageLoader)}
     */
    @Test
    @Disabled("TODO: fix not communicatimg issue")
    void testUpdateView() {
        // Arrange
        Graphics2D mockedGraphics = mock(Graphics2D.class);
        TileImageLoader mockedLoader = mock(TileImageLoader.class);

        // Correct method name and parameters
        when(mockedLoader.getImage(any(TileType.class), anyInt())).thenReturn(new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB));

        // Act
        try {
            TileController tileController = null;
            tileController.updateView();
        } catch (NullPointerException e) {
            fail("Graphics2D mock was not used correctly, causing a NullPointerException.");
        }

        // Assert
        verify(mockedGraphics, times(1)).setColor(any()); // Verify that setColor was called on the mock
        verify(mockedGraphics, times(1)).drawImage(any(), anyInt(), anyInt(), anyInt(), anyInt(), any(), any()); // Verify that drawImage was called
        // Add more verifications as needed
    }
}
